# Generated by Django 4.1.7 on 2023-05-04 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scenic_plot',
            fields=[
                ('plot_id', models.IntegerField(primary_key=True, serialize=False)),
                ('plot_name', models.CharField(max_length=50, null=True)),
                ('plot_address', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('staff_id', models.IntegerField(primary_key=True, serialize=False)),
                ('join_id', models.DateTimeField()),
                ('name', models.CharField(max_length=50, null=True)),
                ('username', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('scenic_plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.scenic_plot')),
            ],
        ),
    ]
