# Generated by Django 4.1.7 on 2023-05-04 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_area_name_delete_work_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='name',
            new_name='report',
        ),
    ]
