# Generated by Django 4.1.7 on 2023-05-04 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_area_report_work_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintain_personnel',
            name='id',
        ),
        migrations.RemoveField(
            model_name='security_personnel',
            name='id',
        ),
        migrations.AlterField(
            model_name='maintain_personnel',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.staff'),
        ),
        migrations.AlterField(
            model_name='security_personnel',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.staff'),
        ),
    ]
