# Generated by Django 4.1.7 on 2023-05-09 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_maintain_personnel_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='crowdvis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_count', models.IntegerField()),
                ('vis_count', models.IntegerField()),
                ('in_count', models.IntegerField()),
                ('out_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='device',
            fields=[
                ('device_id', models.IntegerField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=100, null=True)),
                ('manufacturer', models.CharField(max_length=100, null=True)),
                ('production_date', models.DateTimeField()),
                ('function', models.CharField(max_length=200, null=True)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.area')),
            ],
        ),
        migrations.CreateModel(
            name='maintain_report',
            fields=[
                ('mreport_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mreport_date', models.DateTimeField()),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.maintain_personnel')),
            ],
        ),
        migrations.CreateModel(
            name='maintain_report_device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mreport', models.CharField(max_length=500, null=True)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.device')),
                ('mreport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.maintain_report')),
            ],
        ),
        migrations.CreateModel(
            name='security_report',
            fields=[
                ('sreport_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sreport_date', models.DateTimeField()),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.security_personnel')),
            ],
        ),
        migrations.CreateModel(
            name='security_report_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sreport', models.CharField(max_length=500, null=True)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.area')),
                ('sreport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.security_report')),
            ],
        ),
        migrations.DeleteModel(
            name='work_report',
        ),
    ]
