# Generated by Django 4.1.7 on 2023-05-04 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_security_personnel_maintain_personnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('area_id', models.IntegerField(primary_key=True, serialize=False)),
                ('area_device', models.CharField(max_length=100, null=True)),
                ('area_name', models.CharField(max_length=50, null=True)),
                ('plot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.scenic_plot')),
            ],
        ),
        migrations.CreateModel(
            name='work_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_date', models.DateTimeField()),
                ('report', models.CharField(max_length=200, null=True)),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.area')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.staff')),
            ],
            options={
                'unique_together': {('area_id', 'staff_id')},
            },
        ),
    ]
