# Generated by Django 4.1.7 on 2023-05-04 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_area_work_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_report',
            name='id',
        ),
        migrations.AlterField(
            model_name='work_report',
            name='area_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.area'),
        ),
    ]
