# Generated by Django 4.1.7 on 2023-05-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_work_report_id_alter_work_report_area_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='name',
            field=models.ManyToManyField(to='app.security_personnel'),
        ),
        migrations.DeleteModel(
            name='work_report',
        ),
    ]
