# Generated by Django 4.1.7 on 2023-05-09 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_crowdvis_device_maintain_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdvis',
            name='device_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.device'),
        ),
        migrations.CreateModel(
            name='warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warn_time', models.DateTimeField()),
                ('warn_type', models.CharField(max_length=50, null=True)),
                ('warn_area', models.CharField(max_length=50, null=True)),
                ('warn_description', models.CharField(max_length=50, null=True)),
                ('info', models.CharField(max_length=50, null=True)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.device')),
            ],
        ),
    ]
