# Generated by Django 4.1.7 on 2023-05-23 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_crowdvis_device_id_warning'),
    ]

    operations = [
        migrations.CreateModel(
            name='trace_tabel_staff',
            fields=[
                ('user_id', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('staff_id', models.IntegerField(primary_key=True, serialize=False)),
                ('join_id', models.DateTimeField()),
                ('name', models.CharField(max_length=50, null=True)),
                ('username', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('scenic_plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.scenic_plot')),
            ],
        ),
    ]
